Fix RuboCop NameError.
After updating to latest RuboCop trying to run rake gives the following
error:

    NameError: uninitialized constant Rubocop

This is because they changed to CamelCase naming.